[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.120.3" # Replace with your version if different
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200