baseURL = "https://johnze.co.uk/"
languageCode = "en-gb"
title = "JohnZe"
theme = "NGE"

contentDir = "content"

[permalinks]
  blog = "/blog/:year/:slug/"
  projects = "/projects/:year/:slug/"
  ctfs = "/ctfs/:year/:slug/"

[archetypeOverrides]
  blog = "blog/index.md"
  projects = "projects/index.md"
  ctfs = "ctfs/index.md"

[params]
  description = "Personal blog, CTF write-ups and other projects.  its a work in progress"
  author = "JohnZe"

[params.social]
  github = "J0hnze"
  linkedin = ""
  mastodon = "https://infosec.exchange/@Ponix"
  bluesky = "https://bsky.app/profile/johnze.bsky.social"

[params.features]
  syntaxHighlighting = true
  imageOptimization = true
